# Site
name: "JZ Blog"
title: "JZ Blog"
description: "Setting Up"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'joezeng'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: joezeng6@gmail.com

# Authors
authors:
  joe:
    name: Joe
    display_name: Joe
    avatar: 'assets/images/avatar.jpg'
    email: joezeng6@gmail.com
    web: joezeng.me
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
